name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test:ci

  success_status:
    needs: build
    runs-on: ubuntu-latest
    if: success() # this makes sure it only runs if the build succeeded
    steps:
      - name: Set GitHub commit status to success
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const sha = context.sha;

            console.log("Setting commit status to success for SHA: ", sha);

            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state: 'success',
              description: 'CI passed successfully',
              context: 'CI build',
            });
