name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
  success_status:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Set GitHub commit status to success
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo, owner } = context.repo;
            await github.rest.repos.createStatus({
              owner,
              repo,
              sha: context.sha,
              state: 'success',
              description: 'CI passed successfully',
              context: 'CI build'
            });
